= Warsztaty z wielowątkowości w Jawie - CountDownLatch, CyclicBarrier

Hejo! Zapraszam na warsztacik z CountDownLatch i CyclicBarrier!

Warsztat możesz rozwiązać na dwa sposoby. Poruszając się po pakietach w porządku alfabetycznym,
lub przełączać się między poszczególnymi gałęziami. Polecam sposób z gałęziami, ponieważ nie będzie
Cię kusiło podglądanie rozwiązań z przykładów.

W przypadku rozwiązywania na masterze:
Poruszaj się po pakietach w porządku alfabetycznym, czytaj treść, zrozum koncept,
a następnie spróbuj się z zadaniami!

W razie problemów, kombinuj chwilę sam, poczytaj dokumentację, przemyśl rozwiązanie.
Jeżeli dalej będziesz miał problem, wołaj mnie śmiało i postaram się pomóc.

Jestem świadomy tego, że przykłady pewnie nie są idealne.

Starałem się, żeby były stosunkowo proste i obrazowały koncept.

W razie sugestii jak coś ulepszyć, proszę o kwit GitHubowy.

Warsztat powinien zająć między 90-120 minut.

Jeżeli się spodoba, zachęcam do odznaczek ;D jeżeli się nie podobało, piszcie śmiało co mogę zrobić lepiej następnym razem.

Jeżeli chcesz przejść warsztat poruszając się po gałęziach, wykonaj polecenie git checkout countDownLatchWprowadzenie

Powodzonka!